/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleTokenSol from "./Simple_Token.sol";
export type { simpleTokenSol };
export type { Staking } from "./Staking";
